# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'master'
    
pool:
  vmImage: ubuntu-latest
  demands:
  - maven

variables:
  imageName: 'jettypetclinic'
  dockerhubNS: 'robinmohandevoteam' 

steps:

- script: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    sudo apt-get install apt-transport-https
    echo "deb https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-8.x.list
    sudo apt-get update && sudo apt-get install filebeat
    sudo systemctl enable filebeat
    sudo cp -r ./filebeat/* /etc/filebeat/
    sudo filebeat enable logstash
    sudo filebeat test conf
    sudo filebeat test output
    sudo systemctl start filebeat

- script: |
    ls /
    ls /etc/
    ls /etc/filebeat



- task: UsePythonVersion@0
  displayName: 'Use Python 3.8 (for pytest in mvn)'
  inputs:
    versionSpec: '3.8'
    addToPath: true

- script: |
   python -m pip install --upgrade pip
   pip install selenium
   pip install pytest
   pip install pytest-html
   pip install pytest-json-report
   pip install pytest-elk-reporter


  #  pip install chromedriver-py==88.0.4324.96
  #  pip install pytest-xdist
  #  pip install pytest-nunit
  #  pip install chromedriver_py
  #  pip install webdriver_manager

  displayName: 'Install Python plugins (for pytest in mvn)'


- task: MavenAuthenticate@0
  displayName: 'Maven Authenticate'
  inputs:
    artifactsFeeds: petclinic

- task: Maven@3
  displayName: 'Maven Package'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: '--log-file ./mvn.log'
    
- task: Maven@3
  displayName: 'Maven Test'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'

- task: Maven@3
  displayName: 'Maven Verify'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'verify'